---
- name: Create Docker network
  community.docker.docker_network:
    name: my_network
    driver: bridge
    ipam_config:
      - subnet: 172.25.0.0/16
  vars:
    ansible_python_interpreter: /usr/bin/python3

