---
# tasks file for ansible/roles/launch_database
- name: Launch PostgreSQL container
  community.docker.docker_container:
    name: postgres
    image: postgres:latest
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    networks:
      - name: my_network

